spring:
  cloud:
    stream:
      bindings:
        supply-out-0:
          destination: topic1
      dapr:
        bindings:
          supply-out-0:
            producer:
              pubsubName: kafka-pubsub
