spring:
  cloud:
    stream:
      function:
        definition: supply;consume
      bindings:
        supply-out-0:
          destination: topic1
        consume-in-0:
          destination: topic1
      dapr:
        bindings:
          supply-out-0:
            producer:
              pubsubName: kafka-pubsub
          consume-in-0:
            consumer:
              pubsubName: kafka-pubsub

grpc:
  server:
    port: 8888